name: CI
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# purpose: Continuous Integration pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run-code-quality:
        description: 'Check code quality?'
        required: false
        type: boolean
        default: false
      run-image-scan:
        description: 'Scan container image?'
        required: false
        type: boolean
        default: false

concurrency:
  group: "${{ github.ref }}-ci"
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  git-check:
    name: Git
    uses: ./.github/workflows/reusable-git-check.yml
    with:
      is-pull-request: ${{ github.event_name == 'pull_request' }}

  markup-lint:
    name: Markup
    uses: devpro/github-workflow-parts/.github/workflows/reusable-markup-lint.yml@37400c6d7def6330265424b598dc1861b136e981

  code-quality:
    name: Code
    needs: git-check
    if: needs.git-check.outputs.app_changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.run-code-quality)
    uses: devpro/github-workflow-parts/.github/workflows/reusable-dotnet-quality.yml@d7663950e52d3056f15214c0f2a9ae1f12a53b44
    with:
      custom-commands: |
        echo "Initialize database (indexes, tenants & users)"
        export MONGODB_URI="mongodb://localhost:27017/tfbackend_dev"
        ./scripts/tfbeadm create-indexes
        ./scripts/tfbeadm create-user admin admin123 dummy
      extra-vars: |
        Application__IsHttpsRedirectionEnabled="false"
      mongodb-enabled: true
      fossa-enabled: true
      sonar-enabled: true
      sonar-organization: ${{ vars.SONAR_ORG }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-project-name: Terraform Backend MongoDB
      workflow-parts-version: d7663950e52d3056f15214c0f2a9ae1f12a53b44
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: read
      pull-requests: write

  image-scan:
    name: Image
    needs: git-check
    if: needs.git-check.outputs.app_changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.run-image-scan)
    uses: devpro/github-workflow-parts/.github/workflows/reusable-container-scan.yml@d7663950e52d3056f15214c0f2a9ae1f12a53b44
    with:
      image-definition: "src/WebApi/Dockerfile"
      image-name: ${{ vars.CONTAINER_IMAGE_NAME }}
      image-path: ${{ vars.CONTAINER_REGISTRY_PATH }}
      image-tag: "${{ needs.git-check.outputs.version_major_minor }}.${{ github.run_id }}"
      max-high-cves: 0
      max-medium-cves: 0
