name: PKG
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# purpose: Continuous Delivery (aka Packaging & Shipping)

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  git-check:
    name: Git
    uses: ./.github/workflows/reusable-git-check.yml

  image-publication:
    name: Image
    needs: git-check
    if: github.event_name == 'workflow_dispatch' || needs.git-check.outputs.app_changed == 'true'
    permissions:
      id-token: write
      contents: read
    uses: devpro/github-workflow-parts/.github/workflows/reusable-container-publication.yml@79ef8b68e376c0cb3df0fc82e25961cc649023db
    with:
      create-latest: ${{ github.ref_name == 'main' }}
      image-definition: "src/WebApi/Dockerfile"
      image-name: ${{ vars.CONTAINER_IMAGE_NAME }}
      image-path: ${{ vars.CONTAINER_REGISTRY_PATH }}
      image-tag: "${{ needs.git-check.outputs.version_major_minor }}.${{ github.run_id }}"
    secrets:
      container-registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
      container-registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
